Выполнено задание 4.15. Больше деталей
htmlacademy-javascript/1995679-kekstagram-26 pull request #4
Opened 2022-06-13 17:41 UTC by AlexeyDemyan

Выполнено задание 4.15. Больше деталей

2022-06-13 18:27 UTC, frontstall requested changes

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +// Функция взята из интернета и доработана
Предыдущий вариант был лучше, так как учитывал возможность передавать аргументы в разном порядке (и это было в ТЗ).

[При объявлении функций используются стрелочные функции.](https://up.htmlacademy.ru/javascript/26/criteries#d5)

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +const messageList = [
[Массивы названы существительными во множественном числе.](https://up.htmlacademy.ru/javascript/26/criteries#b5)

Старайся избегать таких именований, который содержат название структуры данных (list, array, object и т.п.)

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +const namesList = [
[Массивы названы существительными во множественном числе.](https://up.htmlacademy.ru/javascript/26/criteries#b5)

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +function getRandomArrayElement(elements) {
Все функции объявляем стрелочными, кроме случаев, про которые скажут позже.

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +function getRandomMessage() {
При такой реализации возможен вариант, когда оба сообщения будут повторяться. Предлагаю такой алгортим:

1. Перемешиваем массив
2. Берём первые два элемента от него

Задание со звёздочкой: берём не первые два элемента, а в соответствии с ТЗ "один или два элемента" (количество определяется рандомом).

Как перемешать массив: гугли алгоритм Фишера-Йетса (он проще, чем кажется по названию), на крайняк смотри, как реализована функция shuffle в lodash

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +function getPhotoData(i) {
`i` можно использовать только при именовании счётчика в цикле, в других случаях нужно осмысленное название для аргумента.

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +    likes: getRandomPositiveInteger(15, 200),
[Магические числа](https://up.htmlacademy.ru/javascript/26/criteries#d19)

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +        id: i + 1000,
По условию id – случайное неповторяющееся число. На самом деле это не самая простая задача, честно говоря, я предлагаю использовать просто счётчик.

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +        avatar: `img/avatar-${getRandomPositiveInteger(1, 6)}.svg`,
магия

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +      {
Нужна функция генерации коммента

2022-06-13 18:27 UTC, frontstall commented on js/main.js
> +  for (let i = 1; i <= 25; i++) {
магическое число 25

2022-06-15 19:10 UTC, AlexeyDemyan commented on js/main.js
> +// Функция взята из интернета и доработана
Ок, вернул тот вариант который написал сам. Просто подумал, что раз функция от Кекса, то предпочтительней использовать её.

2022-06-15 19:11 UTC, AlexeyDemyan commented on js/main.js
> +const messageList = [
Исправил. Совершенно забыл про регламент, постараюсь придерживаться.

2022-06-15 19:11 UTC, AlexeyDemyan commented on js/main.js
> +const namesList = [
Исправил.

2022-06-15 19:13 UTC, AlexeyDemyan commented on js/main.js
> +function getRandomArrayElement(elements) {
Исправил. Линтер еще ругался, что если после фигурных простой return, то нужно убирать и скобки, и return - поправил.

2022-06-15 19:16 UTC, AlexeyDemyan commented on js/main.js
> +function getRandomMessage() {
По счастливой случайности писал карточную игру давно, и сам додумался до подобного алгоритма) Нашел свой старый проект и вставил своё решение вместо того что предлагают на Stack Overflow. На всякий случай прогнал их через jsbenchme, и моё чуть-чуть быстрее)

2022-06-15 19:16 UTC, AlexeyDemyan commented on js/main.js
> +function getPhotoData(i) {
Исправил

2022-06-15 19:17 UTC, AlexeyDemyan commented on js/main.js
> +    likes: getRandomPositiveInteger(15, 200),
Да, слегка не понял эту часть регламента. Теперь понятно, что имелось в виду, учту.

2022-06-15 19:19 UTC, AlexeyDemyan commented on js/main.js
> +        id: i + 1000,
Исправил - надеюсь, что правильно понял. Про сложности с ID немного в курсе. В Реакте я видел вообще для этого отдельные пакеты подключали.

2022-06-15 19:20 UTC, AlexeyDemyan commented on js/main.js
> +        avatar: `img/avatar-${getRandomPositiveInteger(1, 6)}.svg`,
Исправил

2022-06-15 19:20 UTC, AlexeyDemyan commented on js/main.js
> +      {
Написал

2022-06-15 19:20 UTC, AlexeyDemyan commented on js/main.js
> +  for (let i = 1; i <= 25; i++) {
Исправил

2022-06-16 19:41 UTC, frontstall commented on js/main.js
> +const shuffle = (elements) => {
А надо было Фишера-Йетса реализовать.

2022-06-16 19:41 UTC, frontstall commented on js/main.js
> +const minLikes = 15;
Константы нужно писать UPPER_SNAKE_CASE и выносятся в начало модуля (есть критерий)

2022-06-16 19:41 UTC, merged